----------------------------------------------------------------------------------------------------
-- Star Schema DDL for OT (Company) database
-- Creates surrogate-key dimensions used by FACT_SALES
-- Idempotent: safely drops existing objects before (re)creating
-- Oracle SQL
-- Author: Jan Ritt
-- Date: 2025-10-05
----------------------------------------------------------------------------------------------------

-- Drop existing dimension tables and sequences if present (ignore errors)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_TIME CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_PRODUCT CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_CUSTOMER CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_EMPLOYEE CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_STATUS CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END; / 

-- Sequences not used; dimensions use IDENTITY columns
-- Clean up any leftover sequences from earlier revisions to avoid conflicts
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_TIME_SEQ';     EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_PRODUCT_SEQ';  EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_CUSTOMER_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_EMPLOYEE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_STATUS_SEQ';   EXCEPTION WHEN OTHERS THEN NULL; END; / 

----------------------------------------------------------------------------------------------------
-- DIM_TIME
----------------------------------------------------------------------------------------------------
-- DROP TABLE DIM_TIME CASCADE CONSTRAINT;

CREATE TABLE DIM_TIME (
  ID    NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  YEAR  NUMBER        NOT NULL,
  MONTH NUMBER        NOT NULL,
  DAY   NUMBER        NOT NULL,
  CONSTRAINT UQ_DIM_TIME UNIQUE (YEAR, MONTH, DAY)
);

-- IDENTITY used for DIM_TIME (no sequence)


----------------------------------------------------------------------------------------------------
-- DIM_PRODUCT (denormalized with category)
----------------------------------------------------------------------------------------------------
CREATE TABLE DIM_PRODUCT (
  ID                 NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PRODUCT_NAME       VARCHAR2(255)  NOT NULL,
  CATEGORY_NAME      VARCHAR2(255)  NOT NULL,
  STANDARD_COST      NUMBER(9,2),
  LIST_PRICE         NUMBER(9,2),
  SOURCE_PRODUCT_ID  NUMBER         NOT NULL,
  CONSTRAINT UQ_DIM_PRODUCT_SRC UNIQUE (SOURCE_PRODUCT_ID)
);

-- IDENTITY used for DIM_PRODUCT (no sequence)

----------------------------------------------------------------------------------------------------
-- DIM_CUSTOMER
----------------------------------------------------------------------------------------------------
CREATE TABLE DIM_CUSTOMER (
  ID                  NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CUSTOMER_NAME       VARCHAR2(255)  NOT NULL,
  ADDRESS             VARCHAR2(255),
  WEBSITE             VARCHAR2(255),
  CREDIT_LIMIT        NUMBER(8,2),
  SOURCE_CUSTOMER_ID  NUMBER         NOT NULL,
  CONSTRAINT UQ_DIM_CUSTOMER_SRC UNIQUE (SOURCE_CUSTOMER_ID)
);

-- IDENTITY used for DIM_CUSTOMER (no sequence)

----------------------------------------------------------------------------------------------------
-- DIM_EMPLOYEE (salesperson)
----------------------------------------------------------------------------------------------------
CREATE TABLE DIM_EMPLOYEE (
  ID                   NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  FIRST_NAME           VARCHAR2(255)  NOT NULL,
  LAST_NAME            VARCHAR2(255)  NOT NULL,
  EMAIL                VARCHAR2(255)  NOT NULL,
  PHONE                VARCHAR2(50)   NOT NULL,
  HIRE_DATE            DATE           NOT NULL,
  JOB_TITLE            VARCHAR2(255)  NOT NULL,
  SOURCE_EMPLOYEE_ID   NUMBER         NOT NULL,
  CONSTRAINT UQ_DIM_EMPLOYEE_SRC UNIQUE (SOURCE_EMPLOYEE_ID)
);

-- IDENTITY used for DIM_EMPLOYEE (no sequence)

----------------------------------------------------------------------------------------------------
-- DIM_STATUS (order status as small dimension)
----------------------------------------------------------------------------------------------------
CREATE TABLE DIM_STATUS (
  ID      NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STATUS  VARCHAR2(20)  NOT NULL,
  CONSTRAINT UQ_DIM_STATUS UNIQUE (STATUS)
);

-- IDENTITY used for DIM_STATUS (no sequence)

COMMIT; 
